version: "3.3"
services:
  metabase:
    restart: always
    build: ./metabase
    ports:
      - 3000:3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./.metabase:/metabase-data
  # dashboard:
  #   image: grafana/grafana-oss
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   container_name: grafana
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=cq
      - POSTGRES_DB=cq
    volumes:
      - ./.db:/var/lib/postgresql/data:rw
  cq-cron:
    build: cloudquery
    volumes:
      - ./github.yml:/app/github.yml:ro
    environment:
      - PG_CONNECTION_STRING="postgresql://cq:password123@cq-demo-postgres-1:5432/cq?sslmode=disable"
    env_file:
      - .env
#volumes:
  #grafana_data: {}